### ISSUE TITLE
When installing 

### ISSUE THREAD

**Issue by rvbaelen** [AndrewCapon/HyperPixel4TouchScreen#2]
First let me say i'm a real novice in this matter... :) so i reach out for help: 
Bit of background... trying to install the hyperpixel 4 touch screen on my RPI3b+ wich runs:
`Linux klipper 6.1.0-rpi8-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.73-1+rpt1 (2024-01-25) aarch64`
I got the screen working... but when installing klipperscreen, this happend:

```
Update package data
Hit:1 http://archive.raspberrypi.com/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian bookworm InRelease
Hit:3 http://deb.debian.org/debian-security bookworm-security InRelease
Hit:4 http://deb.debian.org/debian bookworm-updates InRelease
Reading package lists... Done
Checking for broken packages...
Detected broken packages. Attempting to fix
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up goodix-dkms (1.0) ...
Removing old goodix-1.0 DKMS files...
Module goodix 1.0 is not installed for kernel 4.14.52-v7+ (armv7l). Skipping...
Deleting module goodix-1.0 completely from the DKMS tree.

Loading tarball for goodix-1.0
Loading /var/lib/dkms/goodix/1.0/4.14.52-v7+/armv7l...
Creating symlink /var/lib/dkms/goodix/1.0/source -> /usr/src/goodix-1.0
Building for 6.1.0-rpi8-rpi-v8
Building for architecture arm64
Building initial module for 6.1.0-rpi8-rpi-v8
Error! Bad return status for module build on kernel: 6.1.0-rpi8-rpi-v8 (arm64)
Consult /var/lib/dkms/goodix/1.0/build/make.log for more information.
dpkg: error processing package goodix-dkms (--configure):
 installed goodix-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 goodix-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)
Unable to fix broken packages. These must be fixed before KlipperScreen can be installed
```
this is the error log:

```
DKMS make.log for goodix-1.0 for kernel 6.1.0-rpi8-rpi-v8 (arm64)
Fri 23 Feb 22:59:18 CET 2024
make -C /lib/modules/`uname -r`/build KCPPFLAGS="" M=/var/lib/dkms/goodix/1.0/build modules
make[1]: Entering directory '/usr/src/linux-headers-6.1.0-rpi8-rpi-v8'
  CC [M]  /var/lib/dkms/goodix/1.0/build/goodix.o
/var/lib/dkms/goodix/1.0/build/goodix.c:1135:19: error: initialization of ‘void (*)(struct i2c_client *)’ from incompatible pointer type ‘int (*)(struct i2c_client *)’ [-Werror=incompatible-pointer-types]
 1135 |         .remove = goodix_ts_remove,
      |                   ^~~~~~~~~~~~~~~~
/var/lib/dkms/goodix/1.0/build/goodix.c:1135:19: note: (near initialization for ‘goodix_ts_driver.remove’)
cc1: some warnings being treated as errors
make[2]: *** [/usr/src/linux-headers-6.1.0-rpi8-common-rpi/scripts/Makefile.build:255: /var/lib/dkms/goodix/1.0/build/goodix.o] Error 1
make[1]: *** [/usr/src/linux-headers-6.1.0-rpi8-common-rpi/Makefile:2039: /var/lib/dkms/goodix/1.0/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.1.0-rpi8-rpi-v8'
make: *** [Makefile:13: modules] Error 2

```

When installing as stated: `dpkg -i hyperpixel4-goodix-dkms_1.0_all.deb
` i get this error:
```
KMS make.log for goodix-1.0 for kernel 6.1.0-rpi8-rpi-v8 (arm64)
Fri 23 Feb 23:01:53 CET 2024
make -C /lib/modules/`uname -r`/build KCPPFLAGS="" M=/var/lib/dkms/goodix/1.0/build modules
make[1]: Entering directory '/usr/src/linux-headers-6.1.0-rpi8-rpi-v8'
  CC [M]  /var/lib/dkms/goodix/1.0/build/goodix.o
/var/lib/dkms/goodix/1.0/build/goodix.c:1135:19: error: initialization of ‘void (*)(struct i2c_client *)’ from incompatible pointer type ‘int (*)(struct i2c_client *)’ [-Werror=incompatible-pointer-types]
 1135 |         .remove = goodix_ts_remove,
      |                   ^~~~~~~~~~~~~~~~
/var/lib/dkms/goodix/1.0/build/goodix.c:1135:19: note: (near initialization for ‘goodix_ts_driver.remove’)
cc1: some warnings being treated as errors
make[2]: *** [/usr/src/linux-headers-6.1.0-rpi8-common-rpi/scripts/Makefile.build:255: /var/lib/dkms/goodix/1.0/build/goodix.o] Error 1
make[1]: *** [/usr/src/linux-headers-6.1.0-rpi8-common-rpi/Makefile:2039: /var/lib/dkms/goodix/1.0/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.1.0-rpi8-rpi-v8'
make: *** [Makefile:13: modules] Error 2

```

so it looks like an error in the script... but i don't understand the error message.

Could you help me with fixing this error?
Thanks in advance

**Comment by AndrewCapon** [comment]
Hi There,

This is probably all a bit out of date now, have you looked at: https://github.com/pimoroni/hyperpixel4

Cheers

Andy
